### ISSUE TITLE
(node:75988) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! 

### ISSUE THREAD

**Issue by msoutopico** [KevCui/translate-cli#3] opened 2021-02-24 08:23 UTC
I have cloned he repo and installed the two dependencies with `pm i puppeteer-core commander`. When I do `./translate.js -p /usr/bin/chromium-browser Schnappi Das Kleine Krokodil` I get:

```
(node:75988) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /usr/bin/chromium ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/souto/Sync/MT/translate-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/home/souto/Sync/MT/translate-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:75988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

However, the browser app launches when I do `/usr/bin/chromium-browser` in the terminal. 

I am running Ubuntu 20.10 on a Raspberry Pi 400.

**Comment by KevCui** [comment] 2021-02-24 09:05
Hi @msoutopico, I think the problem is coming from `commander`. The way to get `options` is changed recently. I will adapt the change for this script. If you want to use it before the fix, you could change the default chromium path here in the js https://github.com/KevCui/translate-cli/blob/master/translate.js#L16 and put your chromium path.

**Comment by msoutopico** [comment] 2021-02-24 18:59
Thanks for your quick reply. Not sure that's what you meant but I have hard-coded the path to my chromium binary (`/usr/bin/chromium-browser`) in the `translate.js` file and now it seems to work.

**Comment by KevCui** [comment] 2021-02-25 21:15
Hi @msoutopico, this issue should be fixed in the latest commit.

**Closed as completed** 2021-02-25 21:15 UTC
Labels: bug
